[2023-11-05T13:11:17.685+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v01/run_id=manual__2023-11-04T23:49:55.656438+00:00/task_id=3rd_task permission to 509
[2023-11-05T13:11:17.795+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v01/run_id=manual__2023-11-04T23:49:55.656438+00:00/task_id=3rd_task permission to 509
[2023-11-05T13:11:18.352+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_google_data_v01.3rd_task manual__2023-11-04T23:49:55.656438+00:00 [queued]>
[2023-11-05T13:11:18.426+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_google_data_v01.3rd_task manual__2023-11-04T23:49:55.656438+00:00 [queued]>
[2023-11-05T13:11:18.428+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 6
[2023-11-05T13:11:18.517+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 3rd_task> on 2023-11-04 23:49:55.656438+00:00
[2023-11-05T13:11:18.534+0000] {standard_task_runner.py:57} INFO - Started process 28027 to run task
[2023-11-05T13:11:18.541+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_google_data_v01', '3rd_task', 'manual__2023-11-04T23:49:55.656438+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmpi0b3on7m']
[2023-11-05T13:11:18.550+0000] {standard_task_runner.py:85} INFO - Job 165: Subtask 3rd_task
[2023-11-05T13:11:18.732+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v01/run_id=manual__2023-11-04T23:49:55.656438+00:00/task_id=3rd_task permission to 509
[2023-11-05T13:11:18.746+0000] {task_command.py:416} INFO - Running <TaskInstance: fetch_google_data_v01.3rd_task manual__2023-11-04T23:49:55.656438+00:00 [running]> on host 264d7b91d87b
[2023-11-05T13:11:19.113+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='fetch_google_data_v01' AIRFLOW_CTX_TASK_ID='3rd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-04T23:49:55.656438+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-04T23:49:55.656438+00:00'
[2023-11-05T13:11:19.120+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-05T13:11:19.128+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/src/scripts/fetch_automatic_downloads.py']
[2023-11-05T13:11:19.161+0000] {subprocess.py:86} INFO - Output:
[2023-11-05T13:21:11.488+0000] {subprocess.py:93} INFO - Downloading data for:  italy_and_regions
[2023-11-05T13:21:11.493+0000] {subprocess.py:93} INFO - Source url:  https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv
[2023-11-05T13:21:11.498+0000] {subprocess.py:93} INFO - 
[2023-11-05T13:21:11.507+0000] {subprocess.py:93} INFO - File written to:  /opt/***/dags/data/inputs/downloaded/italy_and_regions/2023-11-05/dpc-covid19-ita-regioni.csv
[2023-11-05T13:21:11.511+0000] {subprocess.py:93} INFO - Downloading data for:  nytimes
[2023-11-05T13:21:11.514+0000] {subprocess.py:93} INFO - Source url:  https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv
[2023-11-05T13:21:11.518+0000] {subprocess.py:93} INFO - 
[2023-11-05T13:21:11.525+0000] {subprocess.py:93} INFO - File written to:  /opt/***/dags/data/inputs/downloaded/nytimes/2023-11-05/us-counties.csv
[2023-11-05T13:21:11.532+0000] {subprocess.py:93} INFO - Downloading data for:  our_world_in_data
[2023-11-05T13:21:11.535+0000] {subprocess.py:93} INFO - Source url:  https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv
[2023-11-05T13:21:11.539+0000] {subprocess.py:93} INFO - 
[2023-11-05T13:21:11.542+0000] {subprocess.py:93} INFO - File written to:  /opt/***/dags/data/inputs/downloaded/our_world_in_data/2023-11-05/full_data.csv
[2023-11-05T13:21:11.546+0000] {subprocess.py:93} INFO - Downloading data for:  oxford_policy
[2023-11-05T13:21:11.549+0000] {subprocess.py:93} INFO - Source url:  https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv
[2023-11-05T13:21:11.562+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-05T13:21:11.566+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/src/scripts/fetch_automatic_downloads.py", line 60, in <module>
[2023-11-05T13:21:11.569+0000] {subprocess.py:93} INFO -     output = wget.download(source_url, out_path)
[2023-11-05T13:21:11.574+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/wget.py", line 526, in download
[2023-11-05T13:21:11.577+0000] {subprocess.py:93} INFO -     (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
[2023-11-05T13:21:11.580+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/urllib/request.py", line 247, in urlretrieve
[2023-11-05T13:21:11.587+0000] {subprocess.py:93} INFO -     with contextlib.closing(urlopen(url, data)) as fp:
[2023-11-05T13:21:11.590+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
[2023-11-05T13:21:11.593+0000] {subprocess.py:93} INFO -     return opener.open(url, data, timeout)
[2023-11-05T13:21:11.596+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/urllib/request.py", line 531, in open
[2023-11-05T13:21:11.605+0000] {subprocess.py:93} INFO -     response = meth(req, response)
[2023-11-05T13:21:11.609+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/urllib/request.py", line 640, in http_response
[2023-11-05T13:21:11.613+0000] {subprocess.py:93} INFO -     response = self.parent.error(
[2023-11-05T13:21:11.616+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/urllib/request.py", line 569, in error
[2023-11-05T13:21:11.619+0000] {subprocess.py:93} INFO -     return self._call_chain(*args)
[2023-11-05T13:21:11.628+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
[2023-11-05T13:21:11.632+0000] {subprocess.py:93} INFO -     result = func(*args)
[2023-11-05T13:21:11.643+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
[2023-11-05T13:21:11.668+0000] {subprocess.py:93} INFO -     raise HTTPError(req.full_url, code, msg, hdrs, fp)
[2023-11-05T13:21:11.672+0000] {subprocess.py:93} INFO - urllib.error.HTTPError: HTTP Error 404: Not Found
[2023-11-05T13:21:11.738+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-05T13:21:11.787+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-05T13:21:11.823+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_google_data_v01, task_id=3rd_task, execution_date=20231104T234955, start_date=20231105T131118, end_date=20231105T132111
[2023-11-05T13:21:11.935+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 165 for task 3rd_task (Bash command failed. The command returned a non-zero exit code 1.; 28027)
[2023-11-05T13:21:11.992+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-05T13:21:12.139+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
