[2023-11-09T02:05:26.888+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=export_google_data_v02/run_id=scheduled__2023-11-07T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-09T02:05:27.119+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=export_google_data_v02/run_id=scheduled__2023-11-07T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-09T02:05:27.384+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: export_google_data_v02.3rd_task scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-09T02:05:27.448+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: export_google_data_v02.3rd_task scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-09T02:05:27.453+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-09T02:05:27.714+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 3rd_task> on 2023-11-07 00:00:00+00:00
[2023-11-09T02:05:27.740+0000] {standard_task_runner.py:57} INFO - Started process 2990 to run task
[2023-11-09T02:05:27.754+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'export_google_data_v02', '3rd_task', 'scheduled__2023-11-07T00:00:00+00:00', '--job-id', '464', '--raw', '--subdir', 'DAGS_FOLDER/export_data.py', '--cfg-path', '/tmp/tmpxiydqbaz']
[2023-11-09T02:05:27.763+0000] {standard_task_runner.py:85} INFO - Job 464: Subtask 3rd_task
[2023-11-09T02:05:27.984+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=export_google_data_v02/run_id=scheduled__2023-11-07T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-09T02:05:28.006+0000] {task_command.py:416} INFO - Running <TaskInstance: export_google_data_v02.3rd_task scheduled__2023-11-07T00:00:00+00:00 [running]> on host a4fee2fb2c17
[2023-11-09T02:05:28.368+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='export_google_data_v02' AIRFLOW_CTX_TASK_ID='3rd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-07T00:00:00+00:00'
[2023-11-09T02:05:28.373+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-09T02:05:28.378+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/src/scripts/export_data.py']
[2023-11-09T02:05:28.420+0000] {subprocess.py:86} INFO - Output:
[2023-11-09T02:06:21.274+0000] {subprocess.py:97} INFO - Command exited with return code -9
[2023-11-09T02:06:23.734+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code -9.
[2023-11-09T02:06:23.811+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=export_google_data_v02, task_id=3rd_task, execution_date=20231107T000000, start_date=20231109T020527, end_date=20231109T020623
[2023-11-09T02:06:23.871+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 464 for task 3rd_task (Bash command failed. The command returned a non-zero exit code -9.; 2990)
[2023-11-09T02:06:23.934+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-09T02:06:23.982+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
